language: python
sudo: false
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8
install:
  - travis_retry pip install python-coveralls
  - travis_retry pip install tox
script:
  - tox
after_success:
  - coveralls
