sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - travis_retry pip install python-coveralls
  - travis_retry pip install tox-travis
script: tox
after_success:
  - coveralls
